# Generated by Django 5.2.13 on 2026-04-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_osserverreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='osserverreport',
            name='entity_form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные подформы сущности'),
        ),
    ]
